apiVersion: v1
kind: Secret
metadata:
  name: face-scan-secrets
  namespace: face-scan
type: Opaque
stringData:
  database-url: "postgresql+psycopg2://face:CHANGE_ME@postgres-service:5432/facedb"
  jwt-secret: "CHANGE_ME-use-random-32-char-string"
  s3-access-key: "minioadmin"
  s3-secret-key: "minioadmin123"